# Generated by Django 5.0.2 on 2026-05-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_course_credit_hours_alter_result_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manually entered GPA', max_digits=4, null=True),
        ),
    ]
