# Generated by Django 5.0.2 on 2026-05-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manually entered GPA for this semester', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manually entered cumulative GPA', max_digits=4, null=True),
        ),
    ]
