# Generated by Django 5.0.2 on 2026-05-24 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_semester_gpa_alter_student_gpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gpa',
        ),
        migrations.AddField(
            model_name='result',
            name='manual_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='portal.semester'),
        ),
    ]
