# Generated by Django 5.0.2 on 2026-05-24 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_result_manual_gpa_semesterperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterperformance',
            name='status',
            field=models.CharField(choices=[('Distinction', 'Distinction'), ('Upper Credit', 'Upper Credit'), ('Lower Credit', 'Lower Credit'), ('Average', 'Average'), ('Pass', 'Pass'), ('Repeat', 'Repeat'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='semesterperformance',
            name='gpa',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
    ]
