--
-- PostgreSQL database dump
--

\restrict 00JKXe468ffcAfsjOeJwf0yYoPY6O7VhDDT5zHva7xgEwWJwvUvaSixhIS4lv8E

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
9	pbkdf2_sha256$720000$bxZHmroYGWX3o7GwVPCfhN$UfPB9WBs3IQLMdBLgioMsBn7LzIr9JQxW0dLzVVnc5E=	2026-05-11 09:41:29.312613+02	f	zhao				f	t	2026-03-11 16:53:07.086485+02
8	pbkdf2_sha256$720000$YJTSQD27g1hxxkvgzmyfil$FQRDoU5MelzZkl0/r3zF7Mph0lJXwPpFx0LYUX7xSuk=	2026-05-11 10:16:09.546333+02	f	GFC43/038	Chisomo	Chikowi	kanthitimark@gmail.com	f	t	2026-03-11 12:21:55.721843+02
1	pbkdf2_sha256$720000$xxs6URZzVRgCFrcNrHDzXQ$Q6xBXBHmgJ+Z8/UeKGFRcjTbyJXWojLnxkrP0f2Zn2Y=	2026-05-11 10:15:30.983167+02	t	Mark			kanthitimark@gmail.com	t	t	2026-03-08 16:12:04.702854+02
\.


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 9, true);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- PostgreSQL database dump complete
--

\unrestrict 00JKXe468ffcAfsjOeJwf0yYoPY6O7VhDDT5zHva7xgEwWJwvUvaSixhIS4lv8E

