--
-- PostgreSQL database dump
--

\restrict x5mkMZjjm4WsiCldwfCKZ83FHh4hGz4WRduXwB0jTUFJMsgLKj2tVSVchJHhwzj

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: portal_course; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.portal_course (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    code character varying(20) NOT NULL,
    name character varying(150) NOT NULL,
    credit_hours integer NOT NULL,
    CONSTRAINT portal_course_credit_hours_check CHECK ((credit_hours >= 0))
);


ALTER TABLE public.portal_course OWNER TO postgres;

--
-- Name: portal_course_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.portal_course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portal_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: portal_result; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.portal_result (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    marks double precision,
    course_id bigint NOT NULL,
    semester_id bigint NOT NULL,
    student_id bigint NOT NULL
);


ALTER TABLE public.portal_result OWNER TO postgres;

--
-- Name: portal_result_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.portal_result ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portal_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: portal_semester; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.portal_semester (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(50) NOT NULL,
    year integer NOT NULL,
    CONSTRAINT portal_semester_year_check CHECK ((year >= 0))
);


ALTER TABLE public.portal_semester OWNER TO postgres;

--
-- Name: portal_semester_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.portal_semester ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portal_semester_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: portal_staff; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.portal_staff (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    staff_id character varying(20) NOT NULL,
    department character varying(150) NOT NULL,
    role character varying(100) NOT NULL,
    phone_number character varying(15) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.portal_staff OWNER TO postgres;

--
-- Name: portal_staff_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.portal_staff ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portal_staff_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: portal_student; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.portal_student (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    reg_number character varying(20) NOT NULL,
    program character varying(150) NOT NULL,
    year integer NOT NULL,
    phone_number character varying(15) NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT portal_student_year_check CHECK ((year >= 0))
);


ALTER TABLE public.portal_student OWNER TO postgres;

--
-- Name: portal_student_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.portal_student ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portal_student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add course	7	add_course
26	Can change course	7	change_course
27	Can delete course	7	delete_course
28	Can view course	7	view_course
29	Can add semester	8	add_semester
30	Can change semester	8	change_semester
31	Can delete semester	8	delete_semester
32	Can view semester	8	view_semester
33	Can add staff	9	add_staff
34	Can change staff	9	change_staff
35	Can delete staff	9	delete_staff
36	Can view staff	9	view_staff
37	Can add student	10	add_student
38	Can change student	10	change_student
39	Can delete student	10	delete_student
40	Can view student	10	view_student
41	Can add result	11	add_result
42	Can change result	11	change_result
43	Can delete result	11	delete_result
44	Can view result	11	view_result
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
9	pbkdf2_sha256$720000$bxZHmroYGWX3o7GwVPCfhN$UfPB9WBs3IQLMdBLgioMsBn7LzIr9JQxW0dLzVVnc5E=	2026-05-11 09:41:29.312613+02	f	zhao				f	t	2026-03-11 16:53:07.086485+02
8	pbkdf2_sha256$720000$YJTSQD27g1hxxkvgzmyfil$FQRDoU5MelzZkl0/r3zF7Mph0lJXwPpFx0LYUX7xSuk=	2026-05-11 10:16:09.546333+02	f	GFC43/038	Chisomo	Chikowi	kanthitimark@gmail.com	f	t	2026-03-11 12:21:55.721843+02
1	pbkdf2_sha256$720000$xxs6URZzVRgCFrcNrHDzXQ$Q6xBXBHmgJ+Z8/UeKGFRcjTbyJXWojLnxkrP0f2Zn2Y=	2026-05-11 10:15:30.983167+02	t	Mark			kanthitimark@gmail.com	t	t	2026-03-08 16:12:04.702854+02
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-03-09 06:25:54.87967+02	5	Chisomo Chikowi (GFC43/038)	3		10	1
2	2026-03-09 07:07:54.559693+02	4	GFC43/038	3		4	1
3	2026-03-10 23:55:22.745654+02	6	Chisomo Chikowi (GFC43/038)	3		10	1
4	2026-03-10 23:55:42.578935+02	5	GFC43/038	3		4	1
5	2026-03-11 11:13:38.074402+02	6	GFC43/038	3		4	1
6	2026-03-11 11:14:03.522577+02	7	kanthiti	1	[{"added": {}}]	4	1
7	2026-03-11 11:38:32.99335+02	1	 ()	3		9	1
8	2026-03-11 11:46:43.935621+02	8	 (kanthiti)	2	[{"changed": {"fields": ["Phone number"]}}]	10	1
9	2026-03-11 12:20:04.20563+02	8	 (kanthiti)	2	[{"changed": {"fields": ["Program"]}}]	10	1
10	2026-03-11 12:21:20.173938+02	8	 (kanthiti)	3		10	1
11	2026-03-11 12:21:29.009723+02	7	kanthiti	3		4	1
12	2026-03-11 16:53:07.745519+02	9	zhao	1	[{"added": {}}]	4	1
13	2026-03-11 16:53:29.026549+02	2	 (TFWPJ5RH)	1	[{"added": {}}]	9	1
14	2026-03-29 11:39:14.40476+02	10	 (zhao)	3		10	1
15	2026-05-11 09:44:57.459043+02	1	FBS 111 - Biology	1	[{"added": {}}]	7	1
16	2026-05-11 09:45:29.324395+02	2	FBS 112 - Chemistry	1	[{"added": {}}]	7	1
17	2026-05-11 09:46:04.090525+02	3	FBS 113 - Computer Applications	1	[{"added": {}}]	7	1
18	2026-05-11 09:46:36.308356+02	4	FBS 114 - Mathematics	1	[{"added": {}}]	7	1
19	2026-05-11 09:46:59.289513+02	5	FBS 115 - Physics	1	[{"added": {}}]	7	1
20	2026-05-11 09:47:29.43906+02	6	FBS 116 - Communication Skills	1	[{"added": {}}]	7	1
21	2026-05-11 09:47:57.736593+02	7	FTS 111 - Silviculture I	1	[{"added": {}}]	7	1
22	2026-05-11 09:48:27.693927+02	8	FPS 111 - Forestry Extension (FE) I	1	[{"added": {}}]	7	1
23	2026-05-11 09:49:02.257312+02	1	Semester 1 (2025)	1	[{"added": {}}]	8	1
24	2026-05-11 10:02:37.818791+02	9	Chisomo Chikowi (GFC43/038)	2	[{"changed": {"name": "result", "object": "GFC43/038 - FBS 111", "fields": ["Marks"]}}, {"changed": {"name": "result", "object": "GFC43/038 - FBS 112", "fields": ["Marks"]}}, {"changed": {"name": "result", "object": "GFC43/038 - FBS 113", "fields": ["Marks"]}}, {"changed": {"name": "result", "object": "GFC43/038 - FBS 115", "fields": ["Marks"]}}, {"changed": {"name": "result", "object": "GFC43/038 - FTS 111", "fields": ["Marks"]}}, {"changed": {"name": "result", "object": "GFC43/038 - FPS 111", "fields": ["Marks"]}}]	10	1
25	2026-05-11 10:15:48.437649+02	9	Chisomo Chikowi (GFC43/038)	2	[{"changed": {"name": "result", "object": "GFC43/038 - FTS 111", "fields": ["Marks"]}}]	10	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	portal	course
8	portal	semester
9	portal	staff
10	portal	student
11	portal	result
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-03-08 16:10:02.221046+02
2	auth	0001_initial	2026-03-08 16:10:02.311976+02
3	admin	0001_initial	2026-03-08 16:10:02.342295+02
4	admin	0002_logentry_remove_auto_add	2026-03-08 16:10:02.357684+02
5	admin	0003_logentry_add_action_flag_choices	2026-03-08 16:10:02.365456+02
6	contenttypes	0002_remove_content_type_name	2026-03-08 16:10:02.386354+02
7	auth	0002_alter_permission_name_max_length	2026-03-08 16:10:02.391368+02
8	auth	0003_alter_user_email_max_length	2026-03-08 16:10:02.407497+02
9	auth	0004_alter_user_username_opts	2026-03-08 16:10:02.409031+02
10	auth	0005_alter_user_last_login_null	2026-03-08 16:10:02.42624+02
11	auth	0006_require_contenttypes_0002	2026-03-08 16:10:02.427348+02
12	auth	0007_alter_validators_add_error_messages	2026-03-08 16:10:02.43741+02
13	auth	0008_alter_user_username_max_length	2026-03-08 16:10:02.453829+02
14	auth	0009_alter_user_last_name_max_length	2026-03-08 16:10:02.463078+02
15	auth	0010_alter_group_name_max_length	2026-03-08 16:10:02.474369+02
16	auth	0011_update_proxy_permissions	2026-03-08 16:10:02.486948+02
17	auth	0012_alter_user_first_name_max_length	2026-03-08 16:10:02.490135+02
18	portal	0001_initial	2026-03-08 16:10:02.592951+02
19	portal	0002_alter_course_credit_hours_alter_result_marks	2026-03-08 16:10:02.612054+02
20	sessions	0001_initial	2026-03-08 16:10:02.623733+02
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
0ammhz639tqorgdh27dx9ao5rfb6muiu	e30:1vzRk4:s_ykQmL7GaDwpJAEEz5OmqsI8YCqXlKnQ2qkiYY-0d4	2026-03-23 05:57:16.679046+02
ix9fxmyvg80nrzunm9y3oytnowz1yxwg	.eJxVjEsOwjAMBe-SNYpK0jgxS_Y9Q2U7DimgVupnhbg7VOoCtm9m3sv0tK213xad-yGbi0Fz-t2Y5KHjDvKdxttkZRrXeWC7K_agi-2mrM_r4f4dVFrqt2bKCA06LwqNLx4CJiGJAbh10SOXJhRwrKn1oZyjOEkgjqKKFkYw7w_irzge:1wCZRk:uazS92pXF6fpNl_7-1pQITvbv1-CIHZeTYkTP7W9_KE	2026-04-28 10:48:36.619743+02
x7tphrfcl35vrvjwgvgyhdk1wdeb4kkl	.eJxVjMsOwiAQRf-FtSE8y-DSvd9AGBikaiAp7cr479qkC93ec859sRC3tYZt0BLmzM4M2Ol3w5ge1HaQ77HdOk-9rcuMfFf4QQe_9kzPy-H-HdQ46reetFeIxupSyKBUDsGSTqAcCO-ENRSdy9mgKBMkCRKypAJWkfRSILD3B9XkN1k:1wMLo9:hKeldCJrYviAKeopfqMkqZsySU6zczcfAGsRDQh4Skk	2026-05-25 10:16:09.551338+02
\.


--
-- Data for Name: portal_course; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.portal_course (id, created_at, updated_at, code, name, credit_hours) FROM stdin;
1	2026-05-11 09:44:57.436677+02	2026-05-11 09:44:57.436677+02	FBS 111	Biology	3
2	2026-05-11 09:45:29.324395+02	2026-05-11 09:45:29.324395+02	FBS 112	Chemistry	3
3	2026-05-11 09:46:04.090525+02	2026-05-11 09:46:04.090525+02	FBS 113	Computer Applications	2
4	2026-05-11 09:46:36.308356+02	2026-05-11 09:46:36.308356+02	FBS 114	Mathematics	2
5	2026-05-11 09:46:59.289513+02	2026-05-11 09:46:59.289513+02	FBS 115	Physics	3
6	2026-05-11 09:47:29.437149+02	2026-05-11 09:47:29.437149+02	FBS 116	Communication Skills	2
7	2026-05-11 09:47:57.736593+02	2026-05-11 09:47:57.736593+02	FTS 111	Silviculture I	3
8	2026-05-11 09:48:27.691858+02	2026-05-11 09:48:27.691858+02	FPS 111	Forestry Extension (FE) I	2
\.


--
-- Data for Name: portal_result; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.portal_result (id, created_at, updated_at, marks, course_id, semester_id, student_id) FROM stdin;
4	2026-05-11 09:51:15.270663+02	2026-05-11 09:51:15.270663+02	70	6	1	9
5	2026-05-11 09:51:43.711011+02	2026-05-11 09:51:43.711011+02	73	4	1	9
1	2026-05-11 09:49:30.535927+02	2026-05-11 10:02:37.808243+02	77.6	1	1	9
2	2026-05-11 09:50:02.058581+02	2026-05-11 10:02:37.811244+02	93.1	2	1	9
3	2026-05-11 09:50:33.487235+02	2026-05-11 10:02:37.812197+02	81.2	3	1	9
6	2026-05-11 09:52:12.651693+02	2026-05-11 10:02:37.813239+02	83.8	5	1	9
8	2026-05-11 09:53:09.593177+02	2026-05-11 10:02:37.816713+02	67.8	8	1	9
7	2026-05-11 09:52:45.386564+02	2026-05-11 10:15:48.431641+02	79.6	7	1	9
\.


--
-- Data for Name: portal_semester; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.portal_semester (id, created_at, updated_at, name, year) FROM stdin;
1	2026-05-11 09:49:02.24584+02	2026-05-11 09:49:02.24584+02	Semester 1	2025
\.


--
-- Data for Name: portal_staff; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.portal_staff (id, created_at, updated_at, staff_id, department, role, phone_number, user_id) FROM stdin;
2	2026-03-11 16:53:29.025539+02	2026-03-11 16:53:29.025539+02	TFWPJ5RH	Forestry	Lecturer	0999169227	9
\.


--
-- Data for Name: portal_student; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.portal_student (id, created_at, updated_at, reg_number, program, year, phone_number, user_id) FROM stdin;
11	2026-03-29 11:40:03.155281+02	2026-03-29 11:40:03.155281+02	zhao	Not Assigned	1	N/A	9
9	2026-03-11 12:21:56.259179+02	2026-05-11 10:15:48.42798+02	GFC43/038	Forestry	1	0881938390	8
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 44, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 9, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 25, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 11, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 20, true);


--
-- Name: portal_course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.portal_course_id_seq', 8, true);


--
-- Name: portal_result_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.portal_result_id_seq', 8, true);


--
-- Name: portal_semester_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.portal_semester_id_seq', 1, true);


--
-- Name: portal_staff_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.portal_staff_id_seq', 2, true);


--
-- Name: portal_student_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.portal_student_id_seq', 11, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: portal_course portal_course_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_course
    ADD CONSTRAINT portal_course_code_key UNIQUE (code);


--
-- Name: portal_course portal_course_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_course
    ADD CONSTRAINT portal_course_pkey PRIMARY KEY (id);


--
-- Name: portal_result portal_result_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_result
    ADD CONSTRAINT portal_result_pkey PRIMARY KEY (id);


--
-- Name: portal_result portal_result_student_id_course_id_semester_id_2f17d73b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_result
    ADD CONSTRAINT portal_result_student_id_course_id_semester_id_2f17d73b_uniq UNIQUE (student_id, course_id, semester_id);


--
-- Name: portal_semester portal_semester_name_year_d755517c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_semester
    ADD CONSTRAINT portal_semester_name_year_d755517c_uniq UNIQUE (name, year);


--
-- Name: portal_semester portal_semester_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_semester
    ADD CONSTRAINT portal_semester_pkey PRIMARY KEY (id);


--
-- Name: portal_staff portal_staff_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_staff
    ADD CONSTRAINT portal_staff_pkey PRIMARY KEY (id);


--
-- Name: portal_staff portal_staff_staff_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_staff
    ADD CONSTRAINT portal_staff_staff_id_key UNIQUE (staff_id);


--
-- Name: portal_staff portal_staff_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_staff
    ADD CONSTRAINT portal_staff_user_id_key UNIQUE (user_id);


--
-- Name: portal_student portal_student_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_student
    ADD CONSTRAINT portal_student_pkey PRIMARY KEY (id);


--
-- Name: portal_student portal_student_reg_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_student
    ADD CONSTRAINT portal_student_reg_number_key UNIQUE (reg_number);


--
-- Name: portal_student portal_student_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_student
    ADD CONSTRAINT portal_student_user_id_key UNIQUE (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: portal_course_code_8a38572f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX portal_course_code_8a38572f_like ON public.portal_course USING btree (code varchar_pattern_ops);


--
-- Name: portal_resu_course__260fc1_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX portal_resu_course__260fc1_idx ON public.portal_result USING btree (course_id);


--
-- Name: portal_resu_student_ae2377_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX portal_resu_student_ae2377_idx ON public.portal_result USING btree (student_id, semester_id);


--
-- Name: portal_result_course_id_a11c65f6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX portal_result_course_id_a11c65f6 ON public.portal_result USING btree (course_id);


--
-- Name: portal_result_semester_id_4a73f0cf; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX portal_result_semester_id_4a73f0cf ON public.portal_result USING btree (semester_id);


--
-- Name: portal_result_student_id_d70205bd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX portal_result_student_id_d70205bd ON public.portal_result USING btree (student_id);


--
-- Name: portal_staff_department_7958b918; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX portal_staff_department_7958b918 ON public.portal_staff USING btree (department);


--
-- Name: portal_staff_department_7958b918_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX portal_staff_department_7958b918_like ON public.portal_staff USING btree (department varchar_pattern_ops);


--
-- Name: portal_staff_staff_id_97519964_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX portal_staff_staff_id_97519964_like ON public.portal_staff USING btree (staff_id varchar_pattern_ops);


--
-- Name: portal_student_program_a5422cd9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX portal_student_program_a5422cd9 ON public.portal_student USING btree (program);


--
-- Name: portal_student_program_a5422cd9_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX portal_student_program_a5422cd9_like ON public.portal_student USING btree (program varchar_pattern_ops);


--
-- Name: portal_student_reg_number_4180968c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX portal_student_reg_number_4180968c_like ON public.portal_student USING btree (reg_number varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: portal_result portal_result_course_id_a11c65f6_fk_portal_course_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_result
    ADD CONSTRAINT portal_result_course_id_a11c65f6_fk_portal_course_id FOREIGN KEY (course_id) REFERENCES public.portal_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: portal_result portal_result_semester_id_4a73f0cf_fk_portal_semester_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_result
    ADD CONSTRAINT portal_result_semester_id_4a73f0cf_fk_portal_semester_id FOREIGN KEY (semester_id) REFERENCES public.portal_semester(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: portal_result portal_result_student_id_d70205bd_fk_portal_student_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_result
    ADD CONSTRAINT portal_result_student_id_d70205bd_fk_portal_student_id FOREIGN KEY (student_id) REFERENCES public.portal_student(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: portal_staff portal_staff_user_id_7b052171_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_staff
    ADD CONSTRAINT portal_staff_user_id_7b052171_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: portal_student portal_student_user_id_94591d32_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_student
    ADD CONSTRAINT portal_student_user_id_94591d32_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict x5mkMZjjm4WsiCldwfCKZ83FHh4hGz4WRduXwB0jTUFJMsgLKj2tVSVchJHhwzj

